[colors]
# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false

# Indexed colors include all colors from 16 to 256.
#
# When these are not set, they're filled with sensible defaults.
#
# Example:
#   indexed_colors = [
#     { index = 16, color = "#ff00ff" }
#   ]
#indexed_colors = []

# Transparent cell backgrounds
#
# Whether `window.opacity` applies to all cell backgrounds or only to the default background.
#
# When set to `true`, all cells will be transparent regardless of their background color.
#transparent_background_colors = false

# Colors (Tomorrow Night) - Default colors
[colors.primary]
#background = "#1d1f21"
background = "#000000"
#foreground = "#c5c8c6"

# If the bright foreground color is not set, or `draw_bold_text_with_bright_colors` is `false`,
# the normal foreground color will be used.
#bright_foreground = "#eaeaea"

# The dimmed foreground color is calculated automatically if it is not present.
#dim_foreground = "#828482"

# Colors which should be used to draw the terminal cursor.
#
# Allowed values are CellForeground/CellBackground, which reference the affected cell,
# or hexadecimal colors like #ff00ff.
#[colors.cursor]
#cursor = "CellForeground"
#text = "CellBackground"
# Colors for the cursor when the vi mode is active.
#
# Allowed values are CellForeground/CellBackground, which reference the affected cell,
# or hexadecimal colors like #ff00ff.
#[colors.vi_mode_cursor]
#cursor = "CellForeground"
#text = "CellBackground"

#
# Colors used for the search bar and match highlighting.
#

# Allowed values are CellForeground/CellBackground, which reference the
# affected cell, or hexadecimal colors like #ff00ff.
#[colors.search.matches]
#background = "#ffffff"
#foreground = "#000000"

#[colors.search.focused_match]
#background = "#000000"
#foreground = "#ffffff"

#[colors.search.bar]
#background = "#c5c8c6"
#foreground = "#1d1f21"

#
# Keyboard regex hints
#

# First character in the hint label
#
# Allowed values are CellForeground/CellBackground, which reference the affected cell,
# or hexadecimal colors like #ff00ff.
#[colors.hints.start]
#background = "#e9ff5e"
#foreground = "#1d1f21"

# All characters after the first one in the hint label
#
# Allowed values are CellForeground/CellBackground, which reference the
# affected cell, or hexadecimal colors like #ff00ff.
#[colors.hints.end]
#background = "#e9ff5e"
#foreground = "#1d1f21"

# Line indicator
#
# Color used for the indicator displaying the position in history during search and vi mode.
#
# By default, these will use the opposing primary color.
#[colors.line_indicator]
#background = "None"
#foreground = "None"

# Selection colors
#
# Colors which should be used to draw the selection area.
#
# Allowed values are CellForeground/CellBackground, which reference the affected cell,
# or hexadecimal colors like #ff00ff.
#[colors.selection]
#background = "CellForeground"
#text = "CellBackground"

#[colors.normal]
#black   = "#1d1f21"
#red     = "#cc6666"
#green   = "#b5bd68"
#yellow  = "#f0c674"
#blue    = "#81a2be"
#magenta = "#b294bb"
#cyan    = "#8abeb7"
#white   = "#c5c8c6"

#[colors.bright]
#black   = "#666666"
#red     = "#d54e53"
#green   = "#b9ca4a"
#yellow  = "#e7c547"
#blue    = "#7aa6da"
#magenta = "#c397d8"
#cyan    = "#70c0b1"
#white   = "#eaeaea"

# If the dim colors are not set, they will be calculated automatically based on the `normal` colors.
#[colors.dim]
#black   = "#131415"
#red     = "#864343"
#green   = "#777c44"
#yellow  = "#9e824c"
#blue    = "#556a7d"
#magenta = "#75617b"
#cyan    = "#5b7d78"
#white   = "#828482"
