[font]
# Point size
size = 15.0

# Use built-in font for box drawing characters.
#
# Whether Alacritty will use a custom built-in font for box drawing characters (Unicode points 2500 - 259f).
#builtin_box_drawing = true

[font.normal]
# Default:
#   - (macOS) Menlo
#   - (Linux/BSD) monospace
#   - (Windows) Consolas
family = "JetBrainsMono Nerd Font"
style = "Bold"
#style = "Regular"

[font.bold]
# If the bold family is not specified, it will fall back to the value specified for the normal font.
#family = "monospace"
#style = "Bold"

[font.italic]
# If the italic family is not specified, it will fall back to the value specified for the normal font.
#family = "monospace"
#style = "Italic"

[font.bold_italic]
# If the bold italic family is not specified, it will fall back to the value specified for the normal font.
#family = "monospace"
#style = "Bold Italic"

# Offset is the extra space around each character.
#`offset.y` can be thought of as modifying the line spacing, and `offset.x` as modifying the letter spacing.
[font.offset]
#x = 0
#y = 0

# Glyph offset determines the locations of the glyphs within their cells with the default being at the bottom.
# Increasing `x` moves the glyph to the right, increasing `y` moves the glyph upward.
[font.glyph_offset]
#x = 0
#y = 0
