return {
  "MagicDuck/grug-far.nvim",
  opts = {
    engines = {
      ripgrep = {
        path = "rg",
        extraArgs = "--engine=auto",
      },
    },
    keymaps = {
      abort = { n = "<C-c>" },
      applyNext = { n = "<localleader>j" },
      applyPrev = { n = "<localleader>k" },
      close = { n = "<ESC>" },
      gotoLocation = { n = "<enter>" },
      help = { n = "g?" },
      historyAdd = { n = "<localleader>p" },
      historyOpen = { n = "<C-h>" },
      nextInput = { n = "<tab>" },
      prevInput = { n = "<S-tab>" },
      openLocation = { n = "<localleader>o" },
      openNextLocation = { n = "<down>" },
      openPrevLocation = { n = "<up>" },
      pickHistoryEntry = { n = "<enter>" },
      previewLocation = { n = "<localleader>i" },
      qflist = { n = "<C-q>" },
      refresh = { n = "<C-r>" },
      replace = { n = "<C-enter>" },
      syncFile = { n = "<localleader>v" },
      syncLine = { n = "-" },
      syncLocations = { n = "=" },
      syncNext = { n = "<localleader>n" },
      syncPrev = { n = "<localleader>p" },
      swapEngine = { n = "<C-s>" },
      swapReplacementInterpreter = { n = "<localleader>x" },
      toggleShowCommand = { n = "<localleader>w" },
    },
  },
}
