# using http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -o errexit
set -o pipefail

typeset -U path cdpath fpath manpath # prevent duplicates in paths

unset __HM_SESS_VARS_SOURCED && source /etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh
set -o nounset

mkdir -p $XDG_CACHE_HOME/zsh
mkdir -p $XDG_DATA_HOME/zsh

ZSH_CONFIG_HOME=${ZDOTDIR}
source "${ZSH_CONFIG_HOME}/colours.zsh"
source "${ZSH_CONFIG_HOME}/options.zsh"
source "${ZSH_CONFIG_HOME}/aliases.zsh"
source "${ZSH_CONFIG_HOME}/aliases.agentic.zsh"
source "${ZSH_CONFIG_HOME}/aliases.docker.zsh"
source "${ZSH_CONFIG_HOME}/aliases.git.zsh"
source "${ZSH_CONFIG_HOME}/aliases.k8s.zsh"
source "${ZSH_CONFIG_HOME}/aliases.nix.zsh"
zvm_after_init_commands+=('source "${ZSH_CONFIG_HOME}/bindkeys.zsh"')
source "${ZSH_CONFIG_HOME}/completions.zsh"
source "${ZSH_CONFIG_HOME}/prompt.zsh"
source "${ZSH_CONFIG_HOME}/widgets.zsh"

eval "$(/opt/homebrew/bin/brew shellenv)"
#eval "$(brew shellenv)"
source <(fx --comp zsh)

zsh-defer -c 'eval "$(direnv hook zsh)"'
zsh-defer -c 'eval "$(mise activate zsh)"'
zsh-defer -c 'eval "$(fnox activate zsh)"'
zsh-defer -c 'eval "$(zoxide init --cmd cd zsh)"'

# see https://github.com/zellij-org/zellij/issues/2316
source <(zellij setup --generate-completion zsh | sed '/_zellij "$@"/d')

# OrbStack command-line tools and integration
zsh-defer -c 'source ~/.orbstack/shell/init.zsh 2>/dev/null'

set +o errexit
set +o nounset
