default_provider = "onepass"

[providers.age]
type = "age"
recipients = ["age1dewzp62nhlvgjgfqzj6lrrkp2rj7zg94l9e0962mk9jktxcgjy9q4ht96s"]

[providers.onepass]
type = "1password"

[secrets.OP_SERVICE_ACCOUNT_TOKEN]
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV2ZDRmNBWUp1QzhTdW4rSisxcXVyMjRhbVJKZFkzaHQxWGhWZ0xFaGo4ClUzaFZWZkdhTnE4UW13dFN1SjFReldFMHVENExXZVp0dWpML0JiU0tBalkKLT4gPmI8RygtZ3JlYXNlICp6cmBwIEtDIFtdYS1qT2ggVSUsXjJJCmpmcHJtekdEclI3c3MvMG8wcUxTQmh2SktqcW1Uc0gxWmJ4TFczNkpjUHBPT3hTOURrb3J4YTFsb1VDUkVLdjIKVXo5TnlUUmpXM0lFUDR3a3Q1ZEtORjJxUm40Q0NJR2dYMzFmRmxqamkxSzE4RHd5cUtqYzc3WTh2aUk0akhZCi0tLSBiVThmdUQzYmdxMkMzTHJNanhJd2RIYjZ6Q3drbGhnMitmdy9MOEE4WTdvClxAGHwTPxKeciyaXtQYzPNdcfveMUgWK4FKSFEWh8O+8TVwZFN7G6o2jz70ageacF9o9RZv67W4VgziNsVhqz0vFl5MkzR7IWIBBtolMWr3bgmRg6tDpMpFtu5Mbhs1TCrT0XlIWOOUy+JYvasmaIyNE6IMzEZlOrpEPTJMwkb2xSfI7x7qvtaRV0f/pF9UqWmojIC/GrTq+j9I63bT0cdCwdrFYrYMNIIe2dRpw99x20wNFl3ijyookAaQMeCPP0KIMKfPpnwgpUPuGHPfgAs31d4EKnlvtMRypw2L8Pci5+2m2aLo+qeNJSb2R0kLpZaBk7HBunxy80g70LPFnCsr1KDrQEYBBfslgEy6KG+brZoOgv/erN6gbYk23vyZS5sRRcRXOCLexylTtEY7kcQX5RlAebXXCs3b/LGh+fhMeyX5tRVg3C6sFrFwEPGJ1w0iM3IcJvWLkvMLKYI5A2tlkgMjX6YtZ2+pXl2JqAs8gttoW9IAFaqZ0sv38uWzEWz5uetGitNvG9JOIzgZHcbvgD5QNzSejs+JZ4MwTg2+2vsAIZRfl/IUtjLMjIYichvk52I9+I4P9d7fzArlCLxcQI170hXdBbste46lXgHYW4g5+P/hu9Zw2UPfBi/Y2g6DPw3GqiRZ1JTSn9yO30d5K+GQMWHsH1LUxPG6hDvfSciUmxM9RSiLYrrVK79NH1hf72k5HiOJEE8k3kTERVgmweNltEwpSohq1h3173DeGbYRWSsF32NM+CdL6ldBzbR9EGNKR6Xq+vfs+lqOL6xYVYhQN/zpyeWHaElTVRRPXrrdSRdQ+bIgH6nleY/ajTPLl0jzGv5yH2uBoE6HwTpBCgYz/EwQrwY6xMTkOn/KM2mGstXVpDQeDQvS5SlYQ5jdBK12jZ63GHQIiGVKqsK+4JaNjEAQoK2k8I9eqEhCXMOe3MxVgbNyFb9auwR08vzdo5Ea/omEp8ObmKp0DjQPR70G6Px0CosszwxcTzL25ICiV4ky54kXx1+UAL4JOwlz5Tp7pCaYApKOazOHbf3NIHh5gIT2wmz8wahdtsDULVQlDTpAMa+5BwhOCedTwa3Qm0VXrChfqp+VKLzQRbwVFclHVjthGY3aRpqN9GNuQYw05/GDvHW8vtI4nYTJbn9NCISWR2hKa2yNh5hxndMZpSCZ"

[secrets.GITHUB_API_TOKEN]
provider = "onepass"
description = "used primarily by mise, nix, and devenv"
value = "op://Automation/GitHub API/token"
