---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  # override the terminal font size when in windows or when using sixel.
  terminal_font_size: 16

  # the theme to use by default in every presentation unless overridden.
  theme: catppuccin-dark

  # the image protocol to use.
  image_protocol: kitty-local

typst:
  # the pixels per inch when rendering latex/typst formulas.
  ppi: 300

mermaid:
  # the scale parameter passed to the mermaid CLI (mmdc).
  scale: 5

options:
  # whether slides are automatically terminated when a slide title is found.
  implicit_slide_ends: false

  # the prefix to use for commands.
  command_prefix: "cmd:"

  # show all lists incrementally, by implicitly adding pauses in between elements.
  incremental_lists: false

  # this option tells presenterm you don't care about extra parameters in
  # presentation's front matter. This can be useful if you're trying to load a
  # presentation made for another tool
  strict_front_matter_parsing: false

  # whether to treat a thematic break as a slide end.
  end_slide_shorthand: false

snippet:
  exec:
    # enable code snippet execution. Use at your own risk!
    enable: true

#    custom:
#      # The keys should be the language identifier you'd use in a code block.
#      c++:
#        # The name of the file that will be created with your snippet's contents.
#        filename: "snippet.cpp"
#
#        # A list of environment variables that should be set before building/running your code.
#        environment:
#          MY_ENVIRONMENT_VAR: foo
#
#        # A list of commands that will be run one-by-one in the same directory as the snippet is in.
#        commands:
#          - ["g++", "-std=c++20", "snippet.cpp", "-o", "snippet"]
#          - ["./snippet"]

  render:
    # the number of threads to use when rendering `+render` code snippets.
    threads: 5

bindings:
  # the keys that cause the presentation to move forwards.
  next: ["l", "j", "<right>", "<page_down>", "<down>", " "]

  # the keys that cause the presentation to move forwards fast.
  next_fast: ["n"]

  # the keys that cause the presentation to move backwards.
  previous: ["h", "k", "<left>", "<page_up>", "<up>"]

  # the keys that cause the presentation to move backwards fast
  previous_fast: ["p"]

  # the key binding to jump to the first slide.
  first_slide: ["gg"]

  # the key binding to jump to the last slide.
  last_slide: ["G"]

  # the key binding to jump to a specific slide.
  go_to_slide: ["<number>G"]

  # the key binding to execute a piece of shell code.
  execute_code: ["<c-e>"]

  # the key binding to reload the presentation.
  reload: ["<c-r>"]

  # the key binding to toggle the slide index modal.
  toggle_slide_index: ["<c-p>"]

  # the key binding to toggle the key bindings modal.
  toggle_bindings: ["?"]

  # the key binding to close the currently open modal.
  close_modal: ["<esc>"]

  # the key binding to close the application.
  exit: ["<c-c>", "q"]
