setupVersion: 2
startup:
  quiet: true
  changelogMode: summary
  setupWizard: true
theme:
  dark: dark-catppuccin
  light: light-catppuccin
enabledProviders:
  - opencode-go
  - opencode-zen
  - openrouter
disabledProviders:
  - abliteration
  - aiand
  - aimlapi
  - alibaba-coding-plan
  - alibaba-token-plan
  - amazon-bedrock
  - anthropic
  - azure
  - baseten
  - bedrock-mantle
  - cerebras
  - cline-pass
  - cloudflare-ai-gateway
  - commandcode
  - coreweave
  - cursor
  - deepinfra
  - deepseek
  - devin
  - firepass
  - fireworks
  - github-copilot
  - gitlab-duo
  - gitlab-duo-agent
  - gmi-cloud
  - google
  - google-antigravity
  - google-gemini-cli
  - google-vertex
  - groq
  - huggingface
  - kilo
  - kimi-code
  - lm-studio
  - llama.cpp
  - meta
  - minimax
  - minimax-cn
  - minimax-code
  - minimax-code-cn
  - mistral
  - moonshot
  - muse-code
  - nanogpt
  - novita
  - nvidia
  - ollama
  - ollama-cloud
  - openai
  - openai-codex
  - qianfan
  - qwen-portal
  - sakana
  - synthetic
  - together
  - umans
  - venice
  - vercel-ai-gateway
  - wafer-serverless
  - xai
  - xai-oauth
  - xiaomi
  - xiaomi-token-plan-ams
  - xiaomi-token-plan-cn
  - xiaomi-token-plan-sgp
  - yolo-auto
  - zai
  - zenmux
  - zhipu-coding-plan
symbolPreset: nerd
statusLine:
  separator: powerline-thin
  preset: nerd
terminal:
  showProgress: false
tui:
  textSizing: false
composer:
  shape: claude
hideThinkingBlock: true
defaultThinkingLevel: high
extendedContext: true
memory:
  backend: local
edit:
  mode: hashline
  blockAutoGenerated: true
lsp:
  formatOnWrite: true
  diagnosticsOnEdit: true
browser:
  screenshotDir: ~/Pictures/Screenshots/omp
plan:
  defaultOnStartup: false
task:
  isolation:
    commits: ai
modelRoles:
  default: opencode-go/omen-alpha:high
  tiny: opencode-go/deepseek-v4.1-flash:low
  advisor: opencode-go/glm-5.3:high
retry:
  fallbackChains:
    opencode-go/*:
      - opencode-go/omen-alpha
    opencode-zen/*:
      - opencode-zen/glm-5.3-flash
    openrouter/*:
      - openrouter/z-ai/glm-5.3-flash
omitThinking: true
steeringMode: all
followUpMode: all
interruptMode: immediate
