min_version = { hard = "2026.9.5" }

[settings]
env_shell_expand = true
experimental = true
locked = false
lockfile = true
minimum_release_age = "0s"

[settings.npm]
package_manager = "aube"

[shell_alias]
aliases = "mise shell-alias ls"
tasks = "mise tasks ls --all --extended"
tools = "mise ls --global --outdated"

[tools]
"aqua:smol-machines/smolvm" = "latest"
aube = "latest"
bun = "latest"
fnox = "latest"
"github:kucherenko/jscpd" = "latest"
"github:rivolink/leaf" = "latest"
"github:remotemobprogramming/mob" = "latest"
"github:vladkens/macmon" = "latest"
"github:zeroclaw-labs/zeroclaw" = "latest"
"github:zjrosen/perles" = "latest"
"nix:pkl-lsp" = "latest"
worktrunk = "latest"
television = "latest"
usage = "latest"

[tools."aqua:gastownhall/beads"]
version = "latest"
postinstall = "ln -sf $(mise which bd) $XDG_BIN_HOME/bd"

[tools."github:can1357/oh-my-pi"]
version = "latest"
depends = "bun"
postinstall = """
  omp config init-xdg

  omp plugin marketplace add ayghri/i-have-adhd 2> /dev/null || true
  omp plugin install --force i-have-adhd@i-have-adhd
  omp plugin install --force git:github.com/DietrichGebert/ponytail
  omp plugin install --force github:obra/superpowers
"""

[tools.opencode]
version = "latest"
postinstall = """
  ln -sf ${XDG_CONFIG_HOME}/opencode ~/.config/opencode

  vendor="${XDG_CONFIG_HOME}/opencode/vendor"
  mkdir -p $vender
  git -C $vendor sync https://github.com/ayghri/i-have-adhd
"""

[tools.herdr]
version = "latest"
depends = ["github:can1357/oh-my-pi", "opencode"]
postinstall = """
  herdr integration install omp
  herdr integration install opencode
"""

[env]
FNOX_AGE_KEY_FILE = "~/dev/dotfiles.nix/home/fnox/age.txt"
FNOX_IF_MISSING = "error"
FNOX_SHELL_OUTPUT = "none"
