[settings]
env_shell_expand = true
experimental = true
locked = false
lockfile = true

[shell_alias]
aliases = "mise shell-alias ls"
tasks = "mise tasks ls --all --extended"
tools = "mise ls --all-sources"

[tools]
fnox = "latest"
"github:Dicklesworthstone/beads_rust" = "latest"
"github:Dicklesworthstone/beads_viewer" = "latest"
"github:nearai/ironclaw" = "latest"
"github:remotemobprogramming/mob" = "latest"
"github:zeroclaw-labs/zeroclaw" = "latest"
"github:zjrosen/perles" = "latest"
"nix:pkl-lsp" = "latest"
opencode = "latest"

[env]
FNOX_AGE_KEY_FILE = "~/dev/dotfiles.nix/home/fnox/age.txt"
FNOX_IF_MISSING = "error"
FNOX_SHELL_OUTPUT = "none"
