[metadata]
name = "channels"
description = "Select a TV channel"
requirements = ["tv", "bat"]

[source]
command = [
  '''
    excluded_channels=$(ls $XDG_CONFIG_HOME/television/cable/notready | sed 's/\.toml$//' && echo "bash\ngit")
    tv list-channels | grep -v $excluded_channels
  '''
]
no_sort = true

[preview]
command = "bat -pn --color=always ${TELEVISION_CONFIG:-$XDG_CONFIG_HOME/television}/cable/{}.toml"

[ui]
layout = "landscape"

[keybindings]
enter = "actions:switch-channel"

[actions.switch-channel]
description = "Switch to the selected TV channel"
command = "tv {}"
mode = "execute"
