[metadata]
name = "channels"
description = "Select a TV channel"
requirements = ["tv", "bat"]

[source]
command = ["tv list-channels | grep -vE '^(bash|brew|docker|downloads|files|git|images|opencode|path|zoxide|zsh)'"]
no_sort = true

[preview]
command = "bat -pn --color=always ${TELEVISION_CONFIG:-$XDG_CONFIG_HOME/television}/cable/{}.toml"

[ui]
layout = "landscape"

[keybindings]
enter = "actions:switch-channel"

[actions.switch-channel]
description = "Switch to the selected TV channel"
command = "tv {}"
mode = "execute"
